@startuml
'https://plantuml.com/state-diagram

hide empty description
skinparam linetype ortho

state Initialization #gray {
    state awake as "Awake()"
    state onEnable as "OnEnable()"
    state start as "Start()"
    
    awake -> onEnable
    onEnable -> start
}

state Physics #gray {
    state fixedUpdate as "FixedUpdate()"
    state internalAnimationUpdate as "Internal Animation Update" #lightblue
    state onCollisionXXX as "OnCollisionXXX()"
    
    
    fixedUpdate -> internalAnimationUpdate
    internalAnimationUpdate -> onCollisionXXX
}

state inputEvents as "Input events" #gray {
    state onMouseXXX as "OnMouseXXX()"
}

state GameLogic as "Game Logic" #gray {
    state update as "Update()"
    state internalAnimationUpdate2 as "Internal Animation Update" #lightblue
    state lateUpdate as "LateUpdate()"
    
    
    update -> internalAnimationUpdate2
    internalAnimationUpdate2 -> lateUpdate
}

state sceneRendering as "Scene Rendering" #gray

state gizmoRendering as "Gizmo Rendering" #gray {
    state onDrawGizmos as "OnDrawGizmos()"
}

state Decommissioning #gray {
    state onDisable as "OnDisable()"
    state onDestroy as "OnDestroy()"
    
    onDisable -> onDestroy
}

state internalAnimationUpdate3 as "Internal Animation Update" #lightblue {
    state onAnimatorMove as "OnAnimatorMove()"
    onAnimatorMove --> onAnimatorIK
    state onAnimatorIK as "OnAnimatorIK()"
}

Initialization --> Physics
Physics -up-> Physics
Physics --> inputEvents

GameLogic -[hidden]-> internalAnimationUpdate3
internalAnimationUpdate3 -[hidden]-> Decommissioning

inputEvents --> GameLogic
GameLogic --> sceneRendering
sceneRendering -down-> gizmoRendering
gizmoRendering -[norank]-> Physics
gizmoRendering --> Decommissioning
Decommissioning -[norank]-> Initialization

@enduml