@startuml
'https://plantuml.com/state-diagram

[*] --> Idle : SpawnPedestrian()
Idle --> Walking : setup()

Walking -> SwitchingGoal : current node reached
SwitchingGoal -> Walking : next node set
Arrived <- Walking : final node reached
Arrived -> Walking : new path set

Walking --> [*] : removePedestrian()

state c <<choice>>
state d <<choice>>

Walking --> c : pedestrian within range
c --> AvoidingCollision : dist > SlowDownRadius
c --> SlowingDown : dist < SlowDownRadius

AvoidingCollision -> SlowingDown : dist < SlowDownRadius
SlowingDown -> AvoidingCollision : dist > SlowDownRadius

AvoidingCollision --> d
SlowingDown --> d
Walking <-- d : no pedestrian detected



@enduml